/* 

ratIMU_BNO055.ino

This arduino sketch reads data from the Bosch BNO055 inertial sensor. It also reads events generated by other devices, 
namely the ON/OFF state of arena (sync) LEDs and white noise generated by a speaker.

@bartulem 2020

*/

# include <Wire.h>
# include <Adafruit_Sensor.h>
# include <Adafruit_BNO055.h>
# include <utility/imumaths.h>
# include <math.h>

# define BNO055_SAMPLERATE_DELAY_MS (10) // samples every 10 ms from the sensor (if delay is added at the end)
# define ledPin 0
# define soundPin 2
Adafruit_BNO055 ratIMU = Adafruit_BNO055(); // gives name to IMU

char data[1000];  // number of characters to be printed on a single line
int LED = 0;
int soundvar = 0;

void setup() {
Serial.begin(115200);
pinMode(ledPin, INPUT);
pinMode(soundPin, INPUT);
ratIMU.begin();
delay(1000);
}

void loop() {
int t0 = millis();
uint8_t sys, gyro, accel, mg = 0;
ratIMU.getCalibration(&sys, &gyro, &accel, &mg); 

if (digitalRead(ledPin)){
  LED = 1;
}
else {
  LED = 0;
}
  
if (digitalRead(soundPin)){
  soundvar = 1;    
}
else{
  soundvar = 0;         
}  

imu::Vector<3> linacc = ratIMU.getVector(Adafruit_BNO055::VECTOR_LINEARACCEL);
imu::Vector<3> acc = ratIMU.getVector(Adafruit_BNO055::VECTOR_ACCELEROMETER);
imu::Vector<3> gyr = ratIMU.getVector(Adafruit_BNO055::VECTOR_GYROSCOPE);
imu::Vector<3> mag = ratIMU.getVector(Adafruit_BNO055::VECTOR_MAGNETOMETER);
imu::Vector<3> euler = ratIMU.getVector(Adafruit_BNO055::VECTOR_EULER);
int t1 = millis();
int tAve = 0.5*(t1+t0);

sprintf(data, "%d, %d, %.5f, %.5f, %.5f, %.5f, %.5f, %.5f, %.5f, %.5f, %.5f, %.5f, %.5f, %.5f, %.2f, %.2f, %.2f, %d, %d", t0, tAve, acc.x(), acc.y(), acc.z(), linacc.x(), linacc.y(), linacc.z(), gyr.x(), gyr.y(), gyr.z(), mag.x(), mag.y(), mag.z(), euler.x(), euler.y(), euler.z(), LED, soundvar);
Serial.print(data);
Serial.print(" ,");
Serial.print(sys, DEC);
Serial.print(" ,");
Serial.print(gyro, DEC);
Serial.print(" ,");
Serial.print(accel, DEC);
Serial.print(" ,");
Serial.println(mg, DEC); 
//int t2 = millis();
//delay(abs(BNO055_SAMPLERATE_DELAY_MS-(t2-t0)));
  
}
